// packages/react/src/sql-editor.tsx
import { useEffect, useLayoutEffect, useRef } from 'react'

import { useEditorCacheContext } from './editor-cache-context'
import {
  CreateSQLEditorOptions,
  createSQLEditorInstance
} from '@tidbcloud/tisqleditor'

type SQLEditorProps = CreateSQLEditorOptions & {
  editorId: string
  className?: string
}

export function SQLEditor({
  className,
  editorId,
  theme,
  sqlConfig,
  ...rest
}: SQLEditorProps) {
  const editorContainerRef = useRef<HTMLDivElement>(null)
  const cacheCtx = useEditorCacheContext()

  useLayoutEffect(() => {
    if (!editorContainerRef.current) return

    let editorInst = cacheCtx.cache.getEditor(editorId)
    if (!editorInst) {
      editorInst = createSQLEditorInstance({
        editorId,
        theme,
        sqlConfig,
        ...rest
      })
      cacheCtx.cache.addEditor(editorId, editorInst)
    }

    editorContainerRef.current.appendChild(editorInst.editorView.dom)
    editorInst.editorView.focus()

    return () => {
      if (editorContainerRef.current && editorInst) {
        editorContainerRef.current.removeChild(editorInst.editorView.dom)
      }
    }
  }, [editorId])

  // use `useLayoutEffect` to avoid flicker
  useLayoutEffect(() => {
    cacheCtx.cache.getEditor(editorId)?.changeTheme(theme ?? [])
  }, [editorId, theme])

  useEffect(() => {
    cacheCtx.cache.getEditor(editorId)?.changeSQLConfig(sqlConfig ?? {})
  }, [editorId, sqlConfig])

  return <div className={className} ref={editorContainerRef} />
}

// packages/vue/src/sql-editor.vue
<script setup lang="ts">
import { ref, watch, inject, watchEffect } from 'vue'
import {
  CreateSQLEditorOptions,
  createSQLEditorInstance,
  EditorCache
} from '@tidbcloud/tisqleditor'

type SQLEditorProps = CreateSQLEditorOptions & {
  class?: string
}
const props = defineProps<SQLEditorProps>()

const editorContainerRef = ref<HTMLInputElement | null>(null)
const editorCache = inject('editor-cache', new EditorCache())

function editorIdChange(newId: string, oldId: string) {
  if (!editorContainerRef.value) {
    return
  }
  const oldInst = editorCache.getEditor(oldId)
  if (oldInst) {
    editorContainerRef.value.removeChild(oldInst.editorView.dom)
  }
  let newInst = editorCache.getEditor(newId)
  if (!newInst) {
    const { theme, sqlConfig, ...rest } = props
    newInst = createSQLEditorInstance({
      theme,
      sqlConfig,
      ...rest,
      editorId: newId
    })
    editorCache.addEditor(newId, newInst)
  }
  editorContainerRef.value.appendChild(newInst.editorView.dom)
  newInst.editorView.focus()
}
editorIdChange(props.editorId, '')

watch(() => props.editorId, editorIdChange)

watchEffect(() => {
  editorCache.getEditor(props.editorId)?.changeTheme(props.theme ?? [])
})

watchEffect(() => {
  editorCache.getEditor(props.editorId)?.changeSQLConfig(props.sqlConfig ?? {})
})
</script>

<template>
  <div :class="class" ref="editorContainerRef"></div>
</template>
